/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExaminationSeatAllotment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
         
        showDate();
        showTime();


}
    void showDate(){
    Date d=new Date();
    SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
    date.setText(s.format(d));
}
void showTime()
{
    new Timer(0,new ActionListener(){
      @Override
      public void actionPerformed(ActionEvent e){
          Date d=new Date();
          SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
          time.setText(s.format(d));
      }
    }
    ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        usernametextfield = new javax.swing.JTextField();
        passwordtextfield = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JToggleButton();
        cancelbutton = new javax.swing.JToggleButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("          EXAM SEAT ARRANGEMENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 40, 530, 60);

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-icon.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 150, 70, 70);

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pwd.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 230, 70, 73);

        date.setBackground(new java.awt.Color(102, 102, 255));
        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date);
        date.setBounds(300, 320, 120, 40);

        time.setBackground(new java.awt.Color(51, 51, 255));
        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(time);
        time.setBounds(490, 320, 140, 40);

        usernametextfield.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        usernametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernametextfield);
        usernametextfield.setBounds(480, 166, 160, 40);

        passwordtextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordtextfieldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordtextfield);
        passwordtextfield.setBounds(482, 244, 160, 40);

        loginbutton.setBackground(new java.awt.Color(51, 51, 255));
        loginbutton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("LOGIN");
        loginbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginbutton.setOpaque(true);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton);
        loginbutton.setBounds(310, 380, 300, 50);

        cancelbutton.setBackground(new java.awt.Color(247, 13, 13));
        cancelbutton.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        cancelbutton.setForeground(new java.awt.Color(255, 255, 255));
        cancelbutton.setText("EXIT");
        cancelbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton);
        cancelbutton.setBounds(540, 450, 117, 32);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.jpg"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametextfieldActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        String PASSWORD=passwordtextfield.getText();
        String USERNAME=usernametextfield.getText();
        
        if(PASSWORD.contains("123")&& USERNAME.contains("exam")){
            usernametextfield.setText("");
            passwordtextfield.setText("");
            close();
            mainscreen m= new mainscreen();
            m.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"This password is  wrong!\n click ok and try again.","wrong pass",JOptionPane.ERROR_MESSAGE);
            passwordtextfield.setText("");
            usernametextfield.setText("");
        
        }
        
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void passwordtextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtextfieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
        String PASSWORD=passwordtextfield.getText();
        String USERNAME=usernametextfield.getText();
        
        if(PASSWORD.contains("123")&& USERNAME.contains("exam")){
            usernametextfield.setText("");
            passwordtextfield.setText("");
            close();
            mainscreen m= new mainscreen();
            m.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"This password is  wrong!\n click ok and try again.","wrong pass",JOptionPane.ERROR_MESSAGE);
            passwordtextfield.setText("");
            usernametextfield.setText("");
        
        }
        }
    }//GEN-LAST:event_passwordtextfieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelbutton;
    private javax.swing.JLabel date;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton loginbutton;
    private javax.swing.JPasswordField passwordtextfield;
    private javax.swing.JLabel time;
    private javax.swing.JTextField usernametextfield;
    // End of variables declaration//GEN-END:variables
private void close() {
    WindowEvent winClosing=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
}
}