/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExaminationSeatAllotment;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dellpc
 */
public class mainscreen extends javax.swing.JFrame {

    /**
     * Creates new form mainscreen
     */
    public mainscreen() {
        initComponents();
        showDate();
        showTime();
    }
void showDate(){
    Date d=new Date();
    SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
    date.setText(s.format(d));
}
void showTime()
{
    new Timer(0,new ActionListener(){
      @Override
      public void actionPerformed(ActionEvent e){
          Date d=new Date();
          SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
          time.setText(s.format(d));
      }
    }
    ).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        newstudent = new javax.swing.JMenu();
        addnewstudent = new javax.swing.JMenuItem();
        modifystudent = new javax.swing.JMenuItem();
        txtview = new javax.swing.JMenuItem();
        newbranch = new javax.swing.JMenu();
        addnewbranch = new javax.swing.JMenuItem();
        modifybranch = new javax.swing.JMenuItem();
        txtviewbranch = new javax.swing.JMenuItem();
        newfaculty = new javax.swing.JMenu();
        addnewfaculty = new javax.swing.JMenuItem();
        modifyfaculty = new javax.swing.JMenuItem();
        txtviewfaculty = new javax.swing.JMenuItem();
        newroom = new javax.swing.JMenu();
        addnewroom = new javax.swing.JMenuItem();
        modifyroom = new javax.swing.JMenuItem();
        txtviewroom = new javax.swing.JMenuItem();
        newsubject = new javax.swing.JMenu();
        addnewsubject = new javax.swing.JMenuItem();
        modifysubject = new javax.swing.JMenuItem();
        txtviewsubject = new javax.swing.JMenuItem();
        newtimetable = new javax.swing.JMenu();
        addnewtimetable = new javax.swing.JMenuItem();
        modifytimetable = new javax.swing.JMenuItem();
        txtviewtimetable = new javax.swing.JMenuItem();
        newroomallocation = new javax.swing.JMenu();
        addnewroomallocation = new javax.swing.JMenuItem();
        modifyallocation = new javax.swing.JMenuItem();
        txtviewroomallocation = new javax.swing.JMenuItem();
        txt = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem20.setText("jMenuItem20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEM VIEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 220, 180, 25);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 490, 160, 40);

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SEARCH STUDENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 290, 180, 25);

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DATE WISE VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 360, 180, 25);

        time.setBackground(new java.awt.Color(51, 51, 255));
        time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(time);
        time.setBounds(690, 10, 140, 40);

        date.setBackground(new java.awt.Color(102, 102, 255));
        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 51, 204));
        jPanel1.add(date);
        date.setBounds(540, 10, 120, 40);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainpage.jpg"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(0, 0, 900, 580);

        newstudent.setText("Student");
        newstudent.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                newstudentAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        newstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newstudentActionPerformed(evt);
            }
        });

        addnewstudent.setText("Add New Student");
        addnewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewstudentActionPerformed(evt);
            }
        });
        newstudent.add(addnewstudent);

        modifystudent.setText("Modify Student");
        modifystudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifystudentActionPerformed(evt);
            }
        });
        newstudent.add(modifystudent);

        txtview.setText("View");
        txtview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewActionPerformed(evt);
            }
        });
        newstudent.add(txtview);

        jMenuBar2.add(newstudent);

        newbranch.setText("Branch");

        addnewbranch.setText("Add New Branch");
        addnewbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewbranchActionPerformed(evt);
            }
        });
        newbranch.add(addnewbranch);

        modifybranch.setText("Modify Branch");
        modifybranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybranchActionPerformed(evt);
            }
        });
        newbranch.add(modifybranch);

        txtviewbranch.setText("View");
        txtviewbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewbranchActionPerformed(evt);
            }
        });
        newbranch.add(txtviewbranch);

        jMenuBar2.add(newbranch);

        newfaculty.setText("Faculty");

        addnewfaculty.setText("Add New Faculty");
        addnewfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewfacultyActionPerformed(evt);
            }
        });
        newfaculty.add(addnewfaculty);

        modifyfaculty.setText("Modify Faculty");
        modifyfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyfacultyActionPerformed(evt);
            }
        });
        newfaculty.add(modifyfaculty);

        txtviewfaculty.setText("View");
        txtviewfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewfacultyActionPerformed(evt);
            }
        });
        newfaculty.add(txtviewfaculty);

        jMenuBar2.add(newfaculty);

        newroom.setText("Room");

        addnewroom.setText("Add New Room");
        addnewroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewroomActionPerformed(evt);
            }
        });
        newroom.add(addnewroom);

        modifyroom.setText("Modify Room");
        modifyroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyroomActionPerformed(evt);
            }
        });
        newroom.add(modifyroom);

        txtviewroom.setText("View");
        txtviewroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewroomActionPerformed(evt);
            }
        });
        newroom.add(txtviewroom);

        jMenuBar2.add(newroom);

        newsubject.setText("Subject");

        addnewsubject.setText("Add New Subject");
        addnewsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewsubjectActionPerformed(evt);
            }
        });
        newsubject.add(addnewsubject);

        modifysubject.setText("Modify subject");
        modifysubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifysubjectActionPerformed(evt);
            }
        });
        newsubject.add(modifysubject);

        txtviewsubject.setText("View");
        txtviewsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewsubjectActionPerformed(evt);
            }
        });
        newsubject.add(txtviewsubject);

        jMenuBar2.add(newsubject);

        newtimetable.setText("Timetable");

        addnewtimetable.setText("Add New Timetable");
        addnewtimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewtimetableActionPerformed(evt);
            }
        });
        newtimetable.add(addnewtimetable);

        modifytimetable.setText("Modify Timetable");
        modifytimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifytimetableActionPerformed(evt);
            }
        });
        newtimetable.add(modifytimetable);

        txtviewtimetable.setText("View");
        txtviewtimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewtimetableActionPerformed(evt);
            }
        });
        newtimetable.add(txtviewtimetable);

        jMenuBar2.add(newtimetable);

        newroomallocation.setText("Room allocation");

        addnewroomallocation.setText("Add New Room allocation");
        addnewroomallocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewroomallocationActionPerformed(evt);
            }
        });
        newroomallocation.add(addnewroomallocation);

        modifyallocation.setText("Modify Room allocation");
        modifyallocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyallocationActionPerformed(evt);
            }
        });
        newroomallocation.add(modifyallocation);

        txtviewroomallocation.setText("View");
        txtviewroomallocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewroomallocationActionPerformed(evt);
            }
        });
        newroomallocation.add(txtviewroomallocation);

        txt.setText("view allocations");
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        newroomallocation.add(txt);

        jMenuBar2.add(newroomallocation);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewActionPerformed
      dispose();
        this.hide();new vstudent().show();
    }//GEN-LAST:event_txtviewActionPerformed

    private void txtviewroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewroomActionPerformed
        // TODO add your handling code here:
        dispose();
        vroom r=new vroom();
        r.setVisible(true);
    }//GEN-LAST:event_txtviewroomActionPerformed

    private void modifysubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifysubjectActionPerformed
        // TODO add your handling code here:
        dispose();
        modsubject su=new modsubject();
        su.setVisible(true);
    }//GEN-LAST:event_modifysubjectActionPerformed

    private void txtviewsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewsubjectActionPerformed
        // TODO add your handling code here:
        dispose();
        vsubject su=new vsubject();
        su.setVisible(true);
    }//GEN-LAST:event_txtviewsubjectActionPerformed

    private void modifytimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifytimetableActionPerformed
        // TODO add your handling code here:
        dispose();
        modtimetable tt=new modtimetable();
        tt.setVisible(true);
    }//GEN-LAST:event_modifytimetableActionPerformed

    private void txtviewtimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewtimetableActionPerformed
        // TODO add your handling code here:
        dispose();
        vtimetable tt=new vtimetable();
        tt.setVisible(true);
    }//GEN-LAST:event_txtviewtimetableActionPerformed

    private void txtviewroomallocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewroomallocationActionPerformed
        // TODO add your handling code here:
        dispose();
        vroomallocation ra=new vroomallocation();
        ra.setVisible(true);
    }//GEN-LAST:event_txtviewroomallocationActionPerformed

    private void addnewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewstudentActionPerformed
        // TODO add your handling code here:
        dispose();
        student s=new student();
        s.setVisible(true);
    }//GEN-LAST:event_addnewstudentActionPerformed

    private void modifystudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifystudentActionPerformed
        // TODO add your handling code here:
        dispose();
      modstudent ms=new modstudent();
      ms.setVisible(true);
    }//GEN-LAST:event_modifystudentActionPerformed

    private void modifyfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyfacultyActionPerformed
        // TODO add your handling code here:
        dispose();
        modfaculty f=new modfaculty();
        f.setVisible(true);
       
    }//GEN-LAST:event_modifyfacultyActionPerformed

    private void newstudentAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_newstudentAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_newstudentAncestorMoved

    private void addnewbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewbranchActionPerformed
        dispose();
         branch b=new branch();
        b.setVisible(true);
    }//GEN-LAST:event_addnewbranchActionPerformed

    private void addnewfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewfacultyActionPerformed
       dispose();
        faculty f=new faculty();
        f.setVisible(true);
    }//GEN-LAST:event_addnewfacultyActionPerformed

    private void addnewroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewroomActionPerformed
        dispose();
        room r=new room();
        r.setVisible(true);
    }//GEN-LAST:event_addnewroomActionPerformed

    private void addnewsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewsubjectActionPerformed
dispose();
        subject su=new subject();
        su.setVisible(true);
    }//GEN-LAST:event_addnewsubjectActionPerformed

    private void addnewtimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewtimetableActionPerformed
dispose();        timetable t=new timetable();
        t.setVisible(true);
    }//GEN-LAST:event_addnewtimetableActionPerformed

    private void addnewroomallocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewroomallocationActionPerformed
         dispose();
        roomallocation ra=new roomallocation();
        ra.setVisible(true);
    }//GEN-LAST:event_addnewroomallocationActionPerformed

    private void newstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newstudentActionPerformed
        // TODO add your handling code here:
        dispose();
        student s=new student();
        s.setVisible(true);
    }//GEN-LAST:event_newstudentActionPerformed

    private void modifybranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybranchActionPerformed
        // TODO add your handling code here:
        dispose();
        modbranch b=new modbranch();
        b.setVisible(true);
    }//GEN-LAST:event_modifybranchActionPerformed

    private void txtviewbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewbranchActionPerformed
        // TODO add your handling code here:
        dispose();
        vbranch b=new vbranch();
        b.setVisible(true);
    }//GEN-LAST:event_txtviewbranchActionPerformed

    private void txtviewfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewfacultyActionPerformed
        // TODO add your handling code here:
        dispose();
        vfaculty f=new vfaculty();
        f.setVisible(true);
    }//GEN-LAST:event_txtviewfacultyActionPerformed

    private void modifyroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyroomActionPerformed
        // TODO add your handling code here:
        dispose();
        modroom r=new modroom();
        r.setVisible(true);
    }//GEN-LAST:event_modifyroomActionPerformed

    private void modifyallocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyallocationActionPerformed
        // TODO add your handling code here:
        dispose();
        modroomallocation ra=new modroomallocation();
        ra.setVisible(true);
    }//GEN-LAST:event_modifyallocationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"DO YOU WANT TO EXIT?","CONFIRM",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION)
            {
                this.dispose();
                login l=new login();
        l.setVisible(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
        dispose();
         query1 q=new query1();
        q.setVisible(true);
    }//GEN-LAST:event_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
         query2 q2=new query2();
        q2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
         query3 q3=new query3();
        q3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
         query4 q4=new query4();
        q4.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addnewbranch;
    private javax.swing.JMenuItem addnewfaculty;
    private javax.swing.JMenuItem addnewroom;
    private javax.swing.JMenuItem addnewroomallocation;
    private javax.swing.JMenuItem addnewstudent;
    private javax.swing.JMenuItem addnewsubject;
    private javax.swing.JMenuItem addnewtimetable;
    private javax.swing.JLabel date;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem modifyallocation;
    private javax.swing.JMenuItem modifybranch;
    private javax.swing.JMenuItem modifyfaculty;
    private javax.swing.JMenuItem modifyroom;
    private javax.swing.JMenuItem modifystudent;
    private javax.swing.JMenuItem modifysubject;
    private javax.swing.JMenuItem modifytimetable;
    private javax.swing.JMenu newbranch;
    private javax.swing.JMenu newfaculty;
    private javax.swing.JMenu newroom;
    private javax.swing.JMenu newroomallocation;
    private javax.swing.JMenu newstudent;
    private javax.swing.JMenu newsubject;
    private javax.swing.JMenu newtimetable;
    private javax.swing.JLabel time;
    private javax.swing.JMenuItem txt;
    private javax.swing.JMenuItem txtview;
    private javax.swing.JMenuItem txtviewbranch;
    private javax.swing.JMenuItem txtviewfaculty;
    private javax.swing.JMenuItem txtviewroom;
    private javax.swing.JMenuItem txtviewroomallocation;
    private javax.swing.JMenuItem txtviewsubject;
    private javax.swing.JMenuItem txtviewtimetable;
    // End of variables declaration//GEN-END:variables
}
