/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExaminationSeatAllotment;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anilkumar S K
 */
public class modstudent extends javax.swing.JFrame {

    /**
     * Creates new form modstudent
     */
    public modstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usntextfield = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        semtextfield = new javax.swing.JLabel();
        branchidtextfield = new javax.swing.JLabel();
        nametextfield = new javax.swing.JLabel();
        update = new javax.swing.JToggleButton();
        clear = new javax.swing.JToggleButton();
        delete = new javax.swing.JButton();
        txtback = new javax.swing.JButton();
        txtusn = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtsem = new javax.swing.JTextField();
        txtbid1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        usntextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usntextfield.setForeground(new java.awt.Color(51, 255, 51));
        usntextfield.setText("USN ");
        jPanel1.add(usntextfield);
        usntextfield.setBounds(280, 110, 60, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("      MODIFY STUDENT DETAILS   ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 40, 396, 29);

        semtextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        semtextfield.setForeground(new java.awt.Color(51, 255, 51));
        semtextfield.setText("SEM ");
        jPanel1.add(semtextfield);
        semtextfield.setBounds(280, 220, 60, 30);

        branchidtextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        branchidtextfield.setForeground(new java.awt.Color(51, 255, 51));
        branchidtextfield.setText("BRANCH ID ");
        jPanel1.add(branchidtextfield);
        branchidtextfield.setBounds(280, 280, 120, 30);

        nametextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nametextfield.setForeground(new java.awt.Color(51, 255, 51));
        nametextfield.setText("NAME ");
        jPanel1.add(nametextfield);
        nametextfield.setBounds(280, 160, 80, 30);

        update.setBackground(new java.awt.Color(0, 51, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(310, 380, 105, 31);

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(590, 320, 79, 25);

        delete.setBackground(new java.awt.Color(0, 51, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(470, 380, 101, 31);

        txtback.setBackground(new java.awt.Color(0, 51, 255));
        txtback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtback.setForeground(new java.awt.Color(255, 255, 255));
        txtback.setText("BACK");
        txtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbackActionPerformed(evt);
            }
        });
        jPanel1.add(txtback);
        txtback.setBounds(410, 450, 81, 31);

        txtusn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusnActionPerformed(evt);
            }
        });
        txtusn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusnKeyPressed(evt);
            }
        });
        jPanel1.add(txtusn);
        txtusn.setBounds(470, 110, 150, 30);
        jPanel1.add(txtname);
        txtname.setBounds(470, 160, 150, 30);
        jPanel1.add(txtsem);
        txtsem.setBounds(470, 220, 150, 30);

        txtbid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbid1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtbid1);
        txtbid1.setBounds(470, 280, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customblue.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbid1ActionPerformed

    private void txtusnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusnActionPerformed

    private void txtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbackActionPerformed
        // TODO add your handling code here:
        dispose();
        mainscreen m=new mainscreen();
        m.setVisible(true);
    }//GEN-LAST:event_txtbackActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
            Statement st=con.createStatement();
            String q,u;
            u=txtusn.getText();
            q="delete from student where usn='"+u+"'; ";
           
           
            st.execute(q);
            
            JOptionPane.showMessageDialog(this,"Student details deleted");
            txtusn.setText("");
           txtname.setText("");
           txtsem.setText("");
           txtbid1.setText("");
        }
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,e);
 txtusn.setText("");
  txtname.setText("");
   txtsem.setText("");
    txtbid1.setText("");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtusn.setText("");
        txtname.setText("");
        txtsem.setText("");
        txtbid1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
            Statement st=con.createStatement();
            String q,u,n,s,b;
            u=txtusn.getText();
            n=txtname.getText();
            s=txtsem.getText();
            b=txtbid1.getText();
            q="update student set name='"+n+"',sem='"+s+"',branch_id='"+b+"' where usn='"+u+"'; ";
            st.execute(q);
            JOptionPane.showMessageDialog(this," details updated successfully");
             txtusn.setText("");
           txtname.setText("");
           txtsem.setText("");
           txtbid1.setText("");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
           txtusn.setText("");
           txtname.setText("");
           txtsem.setText("");
           txtbid1.setText("");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void txtusnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusnKeyPressed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
        String u;
         u=txtusn.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
        
         String display="select * from student where usn='"+u+"';";
          
         PreparedStatement pst=con.prepareStatement(display);
         ResultSet rs=pst.executeQuery(display);
         rs.next();
         txtname.setText(rs.getString("name"));
         txtsem.setText(rs.getString("sem"));
             txtbid1.setText(rs.getString("branch_id"));
         }
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(modstudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtusnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branchidtextfield;
    private javax.swing.JToggleButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nametextfield;
    private javax.swing.JLabel semtextfield;
    private javax.swing.JButton txtback;
    private javax.swing.JTextField txtbid1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsem;
    private javax.swing.JTextField txtusn;
    private javax.swing.JToggleButton update;
    private javax.swing.JLabel usntextfield;
    // End of variables declaration//GEN-END:variables
}
