/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExaminationSeatAllotment;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anilkumar S K
 */
public class modtimetable extends javax.swing.JFrame {

    /**
     * Creates new form modtimetable
     */
    public modtimetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clear = new javax.swing.JToggleButton();
        txtsid = new javax.swing.JTextField();
        txtsession = new javax.swing.JComboBox<>();
        txttime = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("DATE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 200, 48, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("TIME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 260, 47, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("SUBJECT_ ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 130, 118, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("SESSION");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 320, 81, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("MODIFY TIMETABLE DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 50, 357, 29);

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(570, 350, 91, 30);

        txtsid.setMaximumSize(new java.awt.Dimension(10, 10));
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });
        txtsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsidKeyPressed(evt);
            }
        });
        jPanel1.add(txtsid);
        txtsid.setBounds(490, 130, 120, 30);

        txtsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                    ", "  MORNING", "  AFTERNOON" }));
        txtsession.setMaximumSize(new java.awt.Dimension(10, 10));
        txtsession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsessionActionPerformed(evt);
            }
        });
        jPanel1.add(txtsession);
        txtsession.setBounds(490, 310, 130, 30);

        txttime.setMaximumSize(new java.awt.Dimension(10, 10));
        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        jPanel1.add(txttime);
        txttime.setBounds(490, 260, 120, 30);

        delete.setBackground(new java.awt.Color(51, 51, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(480, 410, 101, 31);

        update.setBackground(new java.awt.Color(51, 51, 255));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(290, 410, 105, 31);

        back.setBackground(new java.awt.Color(51, 51, 255));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(390, 490, 81, 31);

        txtdate.setDateFormatString("dd  MM  yyyy");
        txtdate.setMaximumSize(new java.awt.Dimension(10, 10));
        jPanel1.add(txtdate);
        txtdate.setBounds(490, 190, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/custombrown.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtsid.setText("");
        txtdate.setCalendar(null);
        txttime.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtsessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsessionActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
            Statement st=con.createStatement();
            String q,u;
            u=txtsid.getText();
            q="delete from timetable where subject_id='"+u+"' ";
            st.execute(q);
            JOptionPane.showMessageDialog(this,"timetable details deleted");

        }
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
            Statement st=con.createStatement();
            String q,s,d,t,ss;
            s=txtsid.getText();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-YYYY",Locale.getDefault());
                d =sdf.format(txtdate.getDate());
            t=txttime.getText();
            ss=txtsession.getSelectedItem().toString();
            q="update timetable set date='"+d+"',time='"+t+"',session='"+ss+"' where subject_id='"+s+"'; ";
            st.execute(q);
            JOptionPane.showMessageDialog(this,"timetable details updated successfully");

        }
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        mainscreen m=new mainscreen();
        m.setVisible(true);

    }//GEN-LAST:event_backActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void txtsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsidKeyPressed
        // TODO add your handling code here:
         try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
        String u;
         u=txtsid.getText();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
        
         String display="select * from timetable where subject_id='"+u+"';";
          
         PreparedStatement pst=con.prepareStatement(display);
         ResultSet rs=pst.executeQuery(display);
         rs.next();
         txtdate.setDateFormatString("date");
         txttime.setText(rs.getString("time"));
             txtsession.setSelectedItem("session");
         }
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(modstudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtsidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modtimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modtimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modtimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modtimetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modtimetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JToggleButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtsession;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txttime;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
