/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExaminationSeatAllotment;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dellpc
 */
public class student extends javax.swing.JFrame {
 
    private Object jTablel;

    /**
     * Creates new form welcome
     */
    public student() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JToggleButton();
        view = new javax.swing.JButton();
        txtsem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nametextfield = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtbid1 = new javax.swing.JTextField();
        txtusn = new javax.swing.JTextField();
        semtextfield = new javax.swing.JLabel();
        branchidtextfield = new javax.swing.JLabel();
        usntextfield = new javax.swing.JLabel();
        clear = new javax.swing.JToggleButton();
        txtback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        add.setBackground(new java.awt.Color(0, 0, 255));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(330, 370, 73, 31);

        view.setBackground(new java.awt.Color(0, 0, 255));
        view.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view);
        view.setBounds(460, 370, 83, 31);
        jPanel1.add(txtsem);
        txtsem.setBounds(490, 220, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("STUDENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 30, 115, 29);

        nametextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nametextfield.setForeground(new java.awt.Color(255, 0, 0));
        nametextfield.setText("NAME ");
        jPanel1.add(nametextfield);
        nametextfield.setBounds(300, 160, 100, 30);
        jPanel1.add(txtname);
        txtname.setBounds(490, 160, 150, 30);
        jPanel1.add(txtbid1);
        txtbid1.setBounds(490, 280, 150, 30);
        jPanel1.add(txtusn);
        txtusn.setBounds(490, 100, 150, 30);

        semtextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        semtextfield.setForeground(new java.awt.Color(255, 0, 0));
        semtextfield.setText("SEM ");
        jPanel1.add(semtextfield);
        semtextfield.setBounds(300, 220, 43, 30);

        branchidtextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        branchidtextfield.setForeground(new java.awt.Color(255, 0, 0));
        branchidtextfield.setText("BRANCH ID ");
        jPanel1.add(branchidtextfield);
        branchidtextfield.setBounds(300, 280, 110, 30);

        usntextfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usntextfield.setForeground(new java.awt.Color(255, 0, 0));
        usntextfield.setText("USN ");
        jPanel1.add(usntextfield);
        usntextfield.setBounds(300, 100, 43, 30);

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(600, 320, 79, 25);

        txtback.setBackground(new java.awt.Color(0, 0, 255));
        txtback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtback.setForeground(new java.awt.Color(255, 255, 255));
        txtback.setText("BACK");
        txtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbackActionPerformed(evt);
            }
        });
        jPanel1.add(txtback);
        txtback.setBounds(400, 450, 81, 31);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customblue.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        this.hide();new vstudent().show();
    }//GEN-LAST:event_viewActionPerformed

    private void txtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbackActionPerformed
        // TODO add your handling code here:
        dispose();
        mainscreen m=new mainscreen();
        m.setVisible(true);
    }//GEN-LAST:event_txtbackActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtusn.setText("");
        txtname.setText("");
        txtsem.setText("");
        txtbid1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String u,n,s,b;
        u=txtusn.getText();
        n=txtname.getText();
        s=txtsem.getText();
        b=txtbid1.getText();

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examseat","root","");
            Statement st=con.createStatement();
            String q;
            q="insert into student values('"+u+"','"+n+"','"+s+"','"+b+"');";
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(null,"Student added");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            txtusn.setText("");
            txtname.setText("");
            txtsem.setText("");
            txtbid1.setText("");
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton add;
    private javax.swing.JLabel branchidtextfield;
    private javax.swing.JToggleButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nametextfield;
    private javax.swing.JLabel semtextfield;
    private javax.swing.JButton txtback;
    private javax.swing.JTextField txtbid1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsem;
    private javax.swing.JTextField txtusn;
    private javax.swing.JLabel usntextfield;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables

    private ResultSet executeQuery(String q) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
